import {
  Home,
  Airplay,
  Box,
  FolderPlus,
  Command,
  Cloud,
  BarChart,
  Users,
  ShoppingBag,
  List,
  Mail,
  MessageCircle,
  GitPullRequest,
  Monitor,
  Heart,
  Clock,
  Zap,
  CheckSquare,
  Calendar,
  Image,
  HelpCircle,
  Radio,
  Map,
  Edit,
  Sunrise,
  Package,
  Sliders,
  Layout,
  Server,
  Database,
  Search,
  File,
  Layers,
  UserCheck,
  Settings,
  PieChart,
  Archive,
  FileText,
} from "react-feather";

export const MENUITEMS = [
  {
    menutitle: "Electronic Health Record",

    Items: [
      {
        title: "Profile",
        icon: Archive,
        active: true,
        type: "link",
        path: `${process.env.PUBLIC_URL}/ehr/patientProfile`,
      },
      {
        title: "Doctors List",
        icon: Archive,
        active: false,
        type: "link",
        path: `${process.env.PUBLIC_URL}/ehr/doctorList`,
      },
      {
        title: "Patients List",
        icon: Archive,
        active: false,
        type: "link",
        path: `${process.env.PUBLIC_URL}/ehr/patientList`,
      },
        // {
        //   title: "Add Prescription",
        //   icon: Archive,
        //   active: false,
        //   type: "link",
        //   path: `${process.env.PUBLIC_URL}/ehr/addPrescription`,
        // },
      {
        title: "Prescriptions List",
        icon: FileText,
        active: false,
        type: "link",
        path: `${process.env.PUBLIC_URL}/ehr/prescriptionsList`,
      },
      // {
      //   title: "UploadReports",
      //   icon: Archive,
      //   active: false,
      //   type: "link",
      //   path: `${process.env.PUBLIC_URL}/ehr/uploadReports`,
      // },
      {
        title: "Reports List",
        icon: FileText,
        active: false,
        type: "link",
        path: `${process.env.PUBLIC_URL}/ehr/reportsList`,
      },
    ],
  },

  
];
